version: '3.4'

services:
  app:
    image: 'miltronhub/launchsite:1.0.0'
    container_name: launchsite
    hostname: launchsite.dev
    ports:
      - '5000:5000'
      - '4000-4009:4000-4009'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    deploy:
        resources:
          limits:
            cpus: '1.0'
            memory: 1G 